module.exports.page = [
    {
        id: '1',
        text: `<h2>Текст на русском</h2>
        Когда человек сознательно или интуитивно выбирает себе в жизни какую-то цель, жизненную задачу, он невольно дает себе оценку. По тому, ради чего человек живет, можно судить и о его самооценке - низкой или высокой.
        Если человек живет, чтобы приносить людям добро, облегчать их страдания, давать людям радость, то он оценивает себя на уровне этой своей человечности. Он ставит себе цель, достойную человека.
        Только такая цель позволяет человеку прожить свою жизнь с достоинством и получить настоящую радость. Да, радость! Подумайте: если человек ставит себе задачей увеличивать в жизни добро, приносить людям счастье, какие неудачи могут его постигнуть? Не тому помочь? Но много ли людей не нуждаются в помощи?
        Если жить только для себя, своими мелкими заботами о собственном благополучии, то от прожитого не останется и следа. Если же жить для других, то другие сберегут то, чему служил, чему отдавал силы.
        Можно по-разному определять цель своего существования, но цель должна быть. Надо иметь и принципы в жизни. Одно правило в жизни должно быть у каждого человека, в его цели жизни, в его принципах жизни, в его поведении: надо прожить жизнь с достоинством, чтобы не стыдно было вспоминать.
        Достоинство требует доброты, великодушия, умения не быть эгоистом, быть правдивым, хорошим другом, находить радость в помощи другим.
        Ради достоинства жизни надо уметь отказываться от мелких удовольствий и немалых тоже… Уметь извиняться, признавать перед другими ошибку - лучше, чем врать.
        Обманывая, человек прежде всего обманывает самого себя, ибо он думает, что успешно соврал, а люди поняли и из деликатности промолчали.
        Жизнь - прежде всего творчество, но это не значит, что каждый человек, чтобы жить, должен родиться художником, балериной или ученым. Можно творить просто добрую атмосферу вокруг себя. Человек может принести с собой атмосферу подозрительности, какого-то тягостного молчания, а может внести сразу радость, свет. Вот это и есть творчество.
        <h2>check kek</h2>Lorem ipsum, keky keky dolor sit ametconsectetur adipisicing elit. Totam unde sunt accusamus. Quas, nihil officiis earum numquam saepe iure. Hic ad, autem odio nisi voluptatibus animi iure necessitatibus magnam at. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis porro eum voluptatem adipisci nam maxime molestiae fugiat. Repellat soluta commodi facere, cum quos labore consequatur ut, dolore quibusdam ducimus officia. Impedit veritatis iure at fuga nesciunt quia, rerum sunt? Quas unde incidunt cum ab nesciunt sint sequi dolore distinctio perspiciatis, dolorum quam assumenda. Laborum, maxime mollitia nobis odit voluptates dolorum.
        Voluptate quibusdam porro quidem, dicta numquam eius vitae dolore nostrum officia voluptates aut minus ea ipsum eos possimus molestias similique, cum mollitia alias unde praesentium atque fugiat! Doloremque, maxime autem. Accusamus saepe voluptatum placeat cupiditate error dicta neque harum distinctio. Placeat alias aperiam est tempore, error consequatur, excepturi reiciendis nobis autem architecto iusto dolore. Perferendis odio itaque nisi tempora atque!
        <h2>Subtitle one</h2>
        Omnis at tempora ipsam praesentium, vitae 
        <h2>new title</h2>culpa repellat assumenda, mollitia ex ullam nihil, perspiciatis ipsum qui. Sit, quod rem! Ipsa ipsum temporibus eos voluptas, libero consectetur voluptates veritatis possimus corporis. Illum, numquam distinctio molestias vitae cupiditate, autem dolorum voluptas expedita quibusdam temporibus libero quisquam nobis officiis perspiciatis saepe aperiam nulla tempore reiciendis. Magnam ipsa, est qui quam consequuntur laborum dolore. Unde eum tenetur iure ducimus deleniti sed voluptatem ex, consequatur dolorem numquam aperiam facilis ad voluptatum nam, minus aspernatur? Illum molestias, quos laudantium quas odio repellendus vel voluptate minus ipsa. Doloribus et iusto rerum? Repellendus laborum odio optio eius inventore at delectus dignissimos rerum omnis deleniti minus eveniet aspernatur incidunt atque harum aut iusto modi quam, praesentium tempora. Est, qui? Consequuntur accusantium, architecto suscipit, numquam at alias quasi cupiditate expedita maxime tempora commodi laboriosam sit, nisi ex voluptatibus? Laborum asperiores quisquam, debitis saepe tenetur delectus quidem odio a. Nihil, porro? Adipisci, perferendis doloribus. Odit, illo. Reiciendis suscipit quidem laboriosam voluptates consectetur ipsa veritatis provident perspiciatis dolor rerum, totam odio distinctio hic fuga corporis labore molestiae enim aliquid cupiditate asperiores voluptatem.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam unde sunt accusamus. Quas, nihil officiis earum numquam saepe iure. Hic ad, autem odio nisi voluptatibus animi iure necessitatibus magnam at. 
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis porro eum voluptatem adipisci nam maxime molestiae fugiat. Repellat soluta commodi facere, cum quos labore consequatur ut, dolore quibusdam ducimus officia. Impedit veritatis iure at fuga nesciunt quia, rerum sunt? Quas unde incidunt cum ab nesciunt sint sequi dolore distinctio perspiciatis, dolorum quam assumenda. Laborum, maxime mollitia nobis odit voluptates dolorum. Voluptate quibusdam porro quidem, dicta numquam eius vitae dolore nostrum officia voluptates aut minus ea ipsum eos possimus molestias similique, cum mollitia alias unde praesentium atque fugiat! Doloremque, maxime autem. Accusamus saepe voluptatum placeat cupiditate error dicta neque harum distinctio. Placeat alias aperiam est tempore, error consequatur, excepturi reiciendis nobis autem architecto iusto dolore. Perferendis odio itaque nisi tempora atque!
        <h2>lexslox</h2>
        Omnis at tempora ipsam praesentium, vitae culpa repellat assumenda, mollitia ex ullam nihil, perspiciatis ipsum qui. Sit, quod rem! Ipsa ipsum temporibus eos voluptas, libero consectetur voluptates veritatis possimus corporis. Illum, numquam distinctio molestias vitae cupiditate, autem dolorum voluptas expedita quibusdam temporibus libero quisquam nobis officiis perspiciatis saepe aperiam nulla tempore reiciendis. Magnam ipsa, est qui quam consequuntur laborum dolore. Unde eum tenetur iure ducimus deleniti sed voluptatem ex, consequatur dolorem numquam aperiam facilis ad voluptatum nam, minus aspernatur? Illum molestias, quos laudantium quas odio repellendus vel voluptate minus ipsa. Doloribus et iusto rerum? Repellendus laborum odio optio eius inventore at delectus dignissimos rerum omnis deleniti minus eveniet aspernatur incidunt atque harum aut iusto modi quam, praesentium tempora. Est, qui? Consequuntur accusantium, architecto suscipit, numquam at alias quasi cupiditate expedita maxime tempora commodi laboriosam sit, nisi ex voluptatibus? Laborum asperiores quisquam, debitis saepe tenetur delectus quidem odio a. Nihil, porro? Adipisci, perferendis doloribus. Odit, illo. Reiciendis suscipit quidem laboriosam voluptates consectetur ipsa veritatis provident perspiciatis dolor rerum, totam odio distinctio hic fuga corporis labore molestiae enim aliquid cupiditate asperiores voluptatem.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam unde sunt accusamus. Quas, nihil officiis earum numquam saepe iure. Hic ad, autem odio nisi voluptatibus animi iure necessitatibus magnam at. 
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis porro eum voluptatem adipisci nam maxime molestiae fugiat. Repellat soluta commodi facere, cum quos labore consequatur ut, dolore quibusdam ducimus officia. Impedit veritatis iure at fuga nesciunt quia, rerum sunt? Quas unde incidunt cum ab nesciunt sint sequi dolore distinctio perspiciatis, dolorum quam assumenda. Laborum, maxime mollitia nobis odit voluptates dolorum.         Voluptate quibusdam porro quidem, dicta numquam eius vitae dolore nostrum officia voluptates aut minus ea ipsum eos possimus molestias similique, cum mollitia alias unde praesentium atque fugiat! Doloremque, maxime autem. Accusamus saepe voluptatum placeat cupiditate error dicta neque harum distinctio. Placeat alias aperiam est tempore, error consequatur, excepturi reiciendis nobis autem architecto iusto dolore. Perferendis odio itaque nisi tempora atque! 
        <h2>my favourite subtitle</h2>
        Omnis at tempora ipsam praesentium, vitae culpa repellat assumenda, mollitia ex ullam nihil, perspiciatis ipsum qui. Sit, quod rem! Ipsa ipsum temporibus eos voluptas, libero consectetur voluptates veritatis possimus corporis. Illum, numquam distinctio molestias vitae cupiditate, autem dolorum voluptas expedita quibusdam temporibus libero quisquam nobis officiis perspiciatis saepe aperiam nulla tempore reiciendis. Magnam ipsa, est qui quam consequuntur laborum dolore. Unde eum tenetur iure ducimus deleniti sed voluptatem ex, consequatur dolorem numquam aperiam facilis ad voluptatum nam, minus aspernatur? Illum molestias, quos laudantium quas odio repellendus vel voluptate minus ipsa. Doloribus et iusto rerum? Repellendus laborum odio optio eius inventore at delectus dignissimos rerum omnis deleniti minus eveniet aspernatur incidunt atque harum aut iusto modi quam, praesentium tempora. Est, qui?
        Consequuntur accusantium, architecto suscipit, numquam at alias quasi cupiditate expedita maxime tempora commodi laboriosam sit, nisi ex voluptatibus? Laborum asperiores quisquam, debitis saepe tenetur delectus quidem odio a. Nihil, porro?
        Adipisci, perferendis doloribus. Odit, illo. Reiciendis suscipit quidem laboriosam voluptates consectetur ipsa veritatis provident perspiciatis dolor rerum, totam odio distinctio hic fuga corporis labore molestiae enim aliquid cupiditate asperiores voluptatem.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam unde sunt accusamus. Quas, 
        nihil officiis earum numquam saepe iure. Hic ad, autem odio nisi voluptatibus animi iure necessitatibus magnam at. 
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis porro eum voluptatem adipisci nam maxime molestiae fugiat. Repellat soluta commodi facere, cum quos labore consequatur ut, dolore quibusdam ducimus officia. Impedit veritatis iure at fuga nesciunt quia, rerum sunt? Quas unde incidunt cum ab nesciunt sint sequi dolore distinctio perspiciatis, dolorum quam assumenda. Laborum, maxime mollitia nobis odit voluptates dolorum.
        Voluptate quibusdam porro quidem, dicta numquam eius vitae dolore nostrum officia voluptates aut minus ea ipsum eos possimus molestias similique, cum mollitia alias unde praesentium atque fugiat! Doloremque, maxime autem. Accusamus saepe voluptatum placeat cupiditate error dicta neque harum distinctio. Placeat alias aperiam est tempore, error consequatur, excepturi reiciendis nobis autem architecto iusto dolore. Perferendis odio itaque nisi tempora atque!
        <h2>lol kwk</h2>
        Omnis at tempora ipsam praesentium, vitae culpa repellat assumenda, mollitia ex ullam nihil, perspiciatis ipsum qui. Sit, quod rem! Ipsa ipsum temporibus eos voluptas, libero consectetur voluptates veritatis possimus corporis.
        Illum, numquam distinctio molestias vitae cupiditate, autem dolorum voluptas expedita quibusdam temporibus libero quisquam nobis officiis perspiciatis saepe aperiam nulla tempore reiciendis. Magnam ipsa, est qui quam consequuntur laborum dolore.
        Unde eum tenetur iure ducimus deleniti sed voluptatem ex, consequatur dolorem numquam aperiam facilis ad voluptatum nam, minus aspernatur? Illum molestias, quos laudantium quas odio repellendus vel voluptate minus ipsa.
        Doloribus et iusto rerum? Repellendus laborum odio optio eius inventore at delectus dignissimos rerum omnis deleniti minus eveniet aspernatur incidunt atque harum aut iusto modi quam, praesentium tempora. Est, qui?
        Consequuntur accusantium, archi<h2>123</h2>tecto suscipit, numquam at alias quasi cupiditate expedita maxime tempora commodi laboriosam sit, nisi ex voluptatibus? Laborum asperiores quisquam, debitis saepe tenetur delectus quidem odio a. Nihil, porro?
        Adipisci, perferendis doloribus. Odit, illo. Reiciendis suscipit quidem laboriosam voluptates consectetur ipsa veritatis provident perspiciatis dolor rerum, totam odio distinctio hic fuga corporis labore molestiae enim aliquid cupiditate asperiores voluptatem.`,
      },
      {
        id: '2',
        text: `Семанти́ческая сеть — информационная модель предметной области, имеет вид ориентированного графа. Вершины графа соответствуют объектам предметной области, а дуги (рёбра) задают отношения между ними. Объектами могут быть: понятия, события, свойства, процессы. Таким образом, семантическая сеть — это один из способов представления знаний.

        В названии соединены термины из двух наук: семантика в языкознании изучает смысл единиц языка, а сеть в математике представляет собой разновидность графа — набора вершин, соединённых дугами (рёбрами), которым присвоено некоторое число. В семантической сети роль вершин выполняют понятия базы знаний, а дуги (причем направленные) задают отношения между ними. Таким образом, семантическая сеть отражает семантику предметной области в виде понятий и отношений.
        
        Неправильно приравнивать друг другу понятия «Семантическая сеть» и «Семантическая паутина». Хотя эти понятия не эквивалентны, тем не менее, они связаны.
        <h2>История</h2>
Идея систематизации на основе каких-либо семантических отношений предлагалась ещё учёными ранней науки. Примером этого может служить биологическая классификация Карла Линнея 1735 г. Если рассматривать её как семантическую сеть, то в данной классификации используется отношение подмножества, современное AKO (от англ. «A Kind Of», «разновидность»).

Прародителями современных семантических сетей можно считать экзистенциальные графы, предложенные Чарльзом Пирсом в 1909 г. Они использовались для представления логических высказываний в виде особых диаграмм. Пирс назвал этот способ «логикой будущего».

Важным направлением в исследовании сетей стали работы немецкого психолога Отто Зельца 1913 и 1922 гг. В них для организации структур понятий и ассоциаций, а также изучения методов наследования свойств он использовал графы и семантические отношения. Исследователи М. Андерсон (1973), Д. Норман (1975) и другие использовали эти работы для моделирования человеческой памяти и интеллектуальных свойств.

Компьютерные семантические сети были детально разработаны Ричардом Риченсом (англ.) в 1956 году в рамках проекта Кембриджского центра изучения языка по машинному переводу. Процесс машинного перевода подразделяется на 2 части: перевод исходного текста в промежуточную форму представления, а затем эта промежуточная форма транслируется на нужный язык. Такой промежуточной формой как раз и были семантические сети. В 1961 г. появилась работа Мастерман (англ.), в которой она, в частности, определяла базовый словарь для 15000 понятий. Эти исследования были продолжены Робертом Симмонсом (1966), Й. Уилксом (1972) и другими учёными.

Труды по семантическим сетям часто ссылаются на работу американского психолога Росса Квиллиана (Quillian) о «семантической памяти»[2].
<h2>Структура</h2>
Математика позволяет описать большинство явлений в окружающем мире в виде логических высказываний. Семантические сети возникли как попытка визуализации математических формул. Основным представлением для семантической сети является граф. Однако не стоит забывать, что за графическим изображением непременно стоит строгая математическая запись и что обе эти формы отображают одно и то же.

Графическое представление
Основной формой представления семантической сети является граф. Понятия семантической сети записываются в овалах или прямоугольниках и соединяются стрелками с подписями — дугами (см. рис.). Это наиболее удобно воспринимаемая человеком форма. [источник не указан 3420 дней] Её недостатки проявляются, когда мы начинаем строить более сложные сети или пытаемся учесть особенности естественного языка. Схемы семантических сетей, на которых указаны направления навигационных отношений, называют картами знаний, а их совокупность, позволяющая охватить большие участки семантической сети, атласом знания.

Математическая запись
В математике граф представляется множеством вершин V и множеством отношений между ними E. Используя аппарат математической логики, приходим к выводу, что каждая вершина соответствует элементу предметного множества, а дуга — предикату.

Лингвистическая запись
В лингвистике отношения фиксируются в словарях и в тезаурусах. В словарях в определениях через род и видовое отличие родовое понятие занимает определённое место. В тезаурусах в статье каждого термина могут быть указаны все возможные его связи с другими родственными по теме терминами. От таких тезаурусов необходимо отличать тезаурусы информационно - поисковые с перечнями ключевых слов в статьях, которые предназначены для работы дескрипторных поисковых систем.`,
      },
]