module.exports.page = [
    {
        id: 'title_one',
        title: 'temporary fixed title',
        author: 'max sys',
        date: +new Date(),
        relatedArticles: [
          {title: 'relate one'},
          {title: 'relate five'},
          {title: 'relate three'},
          {title: 'relate four'},
        ],
        references: [
          {link: 'http://localhost:4200/page/relate_three', title: 'Lorem, ipsum.'},
          {link: 'https://google.com', title: 'Lorem, ipsum.'},
          {link: '', title: 'Lorem, ipsum.'},
          {link: 'https://habr.com/ru/post/140612/#:~:text=SCSS%20%E2%80%94%20%22%D0%B4%D0%B8%D0%B0%D0%BB%D0%B5%D0%BA%D1%82%22%20%D1%8F%D0%B7%D1%8B%D0%BA%D0%B0%20SASS,%D1%82%D1%80%D0%B0%D0%BD%D1%81%D0%BB%D0%B8%D1%80%D1%83%D0%B5%D1%82%D1%81%D1%8F%20%D0%B2%20%D0%BE%D0%B1%D1%8B%D1%87%D0%BD%D1%8B%D0%B9%20CSS%20%D0%BA%D0%BE%D0%B4.', title: 'Lorem, ipsum.'},
        ],
        tags: [ 'one', 'two', 'three', 'four'],
        text: `<h2>Текст на русском</h2>
        Когда человек сознательно или интуитивно выбирает себе в жизни какую-то цель, жизненную задачу, он невольно дает себе оценку. По тому, ради чего человек живет, можно судить и о его самооценке - низкой или высокой.
        Если человек живет, чтобы приносить людям добро, облегчать их страдания, давать людям радость, то он оценивает себя на уровне этой своей человечности. Он ставит себе цель, достойную человека.
        Только такая цель позволяет человеку прожить свою жизнь с достоинством и получить настоящую радость. Да, радость! Подумайте: если человек ставит себе задачей увеличивать в жизни добро, приносить людям счастье, какие неудачи могут его постигнуть? Не тому помочь? Но много ли людей не нуждаются в помощи?
        Если жить только для себя, своими мелкими заботами о собственном благополучии, то от прожитого не останется и следа. Если же жить для других, то другие сберегут то, чему служил, чему отдавал силы.
        Можно по-разному определять цель своего существования, но цель должна быть. Надо иметь и принципы в жизни. Одно правило в жизни должно быть у каждого человека, в его цели жизни, в его принципах жизни, в его поведении: надо прожить жизнь с достоинством, чтобы не стыдно было вспоминать.
        Достоинство требует доброты, великодушия, умения не быть эгоистом, быть правдивым, хорошим другом, находить радость в помощи другим.
        Ради достоинства жизни надо уметь отказываться от мелких удовольствий и немалых тоже… Уметь извиняться, признавать перед другими ошибку - лучше, чем врать.
        Обманывая, человек прежде всего обманывает самого себя, ибо он думает, что успешно соврал, а люди поняли и из деликатности промолчали.
        Жизнь - прежде всего творчество, но это не значит, что каждый человек, чтобы жить, должен родиться художником, балериной или ученым. Можно творить просто добрую атмосферу вокруг себя. Человек может принести с собой атмосферу подозрительности, какого-то тягостного молчания, а может внести сразу радость, свет. Вот это и есть творчество.
        <h2>check kek</h2>Lorem ipsum, keky keky dolor sit ametconsectetur adipisicing elit. Totam unde sunt accusamus. Quas, nihil officiis earum numquam saepe iure. Hic ad, autem odio nisi voluptatibus animi iure necessitatibus magnam at. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis porro eum voluptatem adipisci nam maxime molestiae fugiat. Repellat soluta commodi facere, cum quos labore consequatur ut, dolore quibusdam ducimus officia. Impedit veritatis iure at fuga nesciunt quia, rerum sunt? Quas unde incidunt cum ab nesciunt sint sequi dolore distinctio perspiciatis, dolorum quam assumenda. Laborum, maxime mollitia nobis odit voluptates dolorum.
        Voluptate quibusdam porro quidem, dicta numquam eius vitae dolore nostrum officia voluptates aut minus ea ipsum eos possimus molestias similique, cum mollitia alias unde praesentium atque fugiat! Doloremque, maxime autem. Accusamus saepe voluptatum placeat cupiditate error dicta neque harum distinctio. Placeat alias aperiam est tempore, error consequatur, excepturi reiciendis nobis autem architecto iusto dolore. Perferendis odio itaque nisi tempora atque!
        <h2>Subtitle one</h2>
        Omnis at tempora ipsam praesentium, vitae 
        <h2>new title</h2>culpa repellat assumenda, mollitia ex ullam nihil, perspiciatis ipsum qui. Sit, quod rem! Ipsa ipsum temporibus eos voluptas, libero consectetur voluptates veritatis possimus corporis. Illum, numquam distinctio molestias vitae cupiditate, autem dolorum voluptas expedita quibusdam temporibus libero quisquam nobis officiis perspiciatis saepe aperiam nulla tempore reiciendis. Magnam ipsa, est qui quam consequuntur laborum dolore. Unde eum tenetur iure ducimus deleniti sed voluptatem ex, consequatur dolorem numquam aperiam facilis ad voluptatum nam, minus aspernatur? Illum molestias, quos laudantium quas odio repellendus vel voluptate minus ipsa. Doloribus et iusto rerum? Repellendus laborum odio optio eius inventore at delectus dignissimos rerum omnis deleniti minus eveniet aspernatur incidunt atque harum aut iusto modi quam, praesentium tempora. Est, qui? Consequuntur accusantium, architecto suscipit, numquam at alias quasi cupiditate expedita maxime tempora commodi laboriosam sit, nisi ex voluptatibus? Laborum asperiores quisquam, debitis saepe tenetur delectus quidem odio a. Nihil, porro? Adipisci, perferendis doloribus. Odit, illo. Reiciendis suscipit quidem laboriosam voluptates consectetur ipsa veritatis provident perspiciatis dolor rerum, totam odio distinctio hic fuga corporis labore molestiae enim aliquid cupiditate asperiores voluptatem.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam unde sunt accusamus. Quas, nihil officiis earum numquam saepe iure. Hic ad, autem odio nisi voluptatibus animi iure necessitatibus magnam at. 
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis porro eum voluptatem adipisci nam maxime molestiae fugiat. Repellat soluta commodi facere, cum quos labore consequatur ut, dolore quibusdam ducimus officia. Impedit veritatis iure at fuga nesciunt quia, rerum sunt? Quas unde incidunt cum ab nesciunt sint sequi dolore distinctio perspiciatis, dolorum quam assumenda. Laborum, maxime mollitia nobis odit voluptates dolorum. Voluptate quibusdam porro quidem, dicta numquam eius vitae dolore nostrum officia voluptates aut minus ea ipsum eos possimus molestias similique, cum mollitia alias unde praesentium atque fugiat! Doloremque, maxime autem. Accusamus saepe voluptatum placeat cupiditate error dicta neque harum distinctio. Placeat alias aperiam est tempore, error consequatur, excepturi reiciendis nobis autem architecto iusto dolore. Perferendis odio itaque nisi tempora atque!
        <h2>lexslox</h2>
        Omnis at tempora ipsam praesentium, vitae culpa repellat assumenda, mollitia ex ullam nihil, perspiciatis ipsum qui. Sit, quod rem! Ipsa ipsum temporibus eos voluptas, libero consectetur voluptates veritatis possimus corporis. Illum, numquam distinctio molestias vitae cupiditate, autem dolorum voluptas expedita quibusdam temporibus libero quisquam nobis officiis perspiciatis saepe aperiam nulla tempore reiciendis. Magnam ipsa, est qui quam consequuntur laborum dolore. Unde eum tenetur iure ducimus deleniti sed voluptatem ex, consequatur dolorem numquam aperiam facilis ad voluptatum nam, minus aspernatur? Illum molestias, quos laudantium quas odio repellendus vel voluptate minus ipsa. Doloribus et iusto rerum? Repellendus laborum odio optio eius inventore at delectus dignissimos rerum omnis deleniti minus eveniet aspernatur incidunt atque harum aut iusto modi quam, praesentium tempora. Est, qui? Consequuntur accusantium, architecto suscipit, numquam at alias quasi cupiditate expedita maxime tempora commodi laboriosam sit, nisi ex voluptatibus? Laborum asperiores quisquam, debitis saepe tenetur delectus quidem odio a. Nihil, porro? Adipisci, perferendis doloribus. Odit, illo. Reiciendis suscipit quidem laboriosam voluptates consectetur ipsa veritatis provident perspiciatis dolor rerum, totam odio distinctio hic fuga corporis labore molestiae enim aliquid cupiditate asperiores voluptatem.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam unde sunt accusamus. Quas, nihil officiis earum numquam saepe iure. Hic ad, autem odio nisi voluptatibus animi iure necessitatibus magnam at. 
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis porro eum voluptatem adipisci nam maxime molestiae fugiat. Repellat soluta commodi facere, cum quos labore consequatur ut, dolore quibusdam ducimus officia. Impedit veritatis iure at fuga nesciunt quia, rerum sunt? Quas unde incidunt cum ab nesciunt sint sequi dolore distinctio perspiciatis, dolorum quam assumenda. Laborum, maxime mollitia nobis odit voluptates dolorum.         Voluptate quibusdam porro quidem, dicta numquam eius vitae dolore nostrum officia voluptates aut minus ea ipsum eos possimus molestias similique, cum mollitia alias unde praesentium atque fugiat! Doloremque, maxime autem. Accusamus saepe voluptatum placeat cupiditate error dicta neque harum distinctio. Placeat alias aperiam est tempore, error consequatur, excepturi reiciendis nobis autem architecto iusto dolore. Perferendis odio itaque nisi tempora atque! 
        <h2>my favourite subtitle</h2>
        Omnis at tempora ipsam praesentium, vitae culpa repellat assumenda, mollitia ex ullam nihil, perspiciatis ipsum qui. Sit, quod rem! Ipsa ipsum temporibus eos voluptas, libero consectetur voluptates veritatis possimus corporis. Illum, numquam distinctio molestias vitae cupiditate, autem dolorum voluptas expedita quibusdam temporibus libero quisquam nobis officiis perspiciatis saepe aperiam nulla tempore reiciendis. Magnam ipsa, est qui quam consequuntur laborum dolore. Unde eum tenetur iure ducimus deleniti sed voluptatem ex, consequatur dolorem numquam aperiam facilis ad voluptatum nam, minus aspernatur? Illum molestias, quos laudantium quas odio repellendus vel voluptate minus ipsa. Doloribus et iusto rerum? Repellendus laborum odio optio eius inventore at delectus dignissimos rerum omnis deleniti minus eveniet aspernatur incidunt atque harum aut iusto modi quam, praesentium tempora. Est, qui?
        Consequuntur accusantium, architecto suscipit, numquam at alias quasi cupiditate expedita maxime tempora commodi laboriosam sit, nisi ex voluptatibus? Laborum asperiores quisquam, debitis saepe tenetur delectus quidem odio a. Nihil, porro?
        Adipisci, perferendis doloribus. Odit, illo. Reiciendis suscipit quidem laboriosam voluptates consectetur ipsa veritatis provident perspiciatis dolor rerum, totam odio distinctio hic fuga corporis labore molestiae enim aliquid cupiditate asperiores voluptatem.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Totam unde sunt accusamus. Quas, 
        nihil officiis earum numquam saepe iure. Hic ad, autem odio nisi voluptatibus animi iure necessitatibus magnam at. 
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perspiciatis porro eum voluptatem adipisci nam maxime molestiae fugiat. Repellat soluta commodi facere, cum quos labore consequatur ut, dolore quibusdam ducimus officia. Impedit veritatis iure at fuga nesciunt quia, rerum sunt? Quas unde incidunt cum ab nesciunt sint sequi dolore distinctio perspiciatis, dolorum quam assumenda. Laborum, maxime mollitia nobis odit voluptates dolorum.
        Voluptate quibusdam porro quidem, dicta numquam eius vitae dolore nostrum officia voluptates aut minus ea ipsum eos possimus molestias similique, cum mollitia alias unde praesentium atque fugiat! Doloremque, maxime autem. Accusamus saepe voluptatum placeat cupiditate error dicta neque harum distinctio. Placeat alias aperiam est tempore, error consequatur, excepturi reiciendis nobis autem architecto iusto dolore. Perferendis odio itaque nisi tempora atque!
        <h2>lol kwk</h2>
        Omnis at tempora ipsam praesentium, vitae culpa repellat assumenda, mollitia ex ullam nihil, perspiciatis ipsum qui. Sit, quod rem! Ipsa ipsum temporibus eos voluptas, libero consectetur voluptates veritatis possimus corporis.
        Illum, numquam distinctio molestias vitae cupiditate, autem dolorum voluptas expedita quibusdam temporibus libero quisquam nobis officiis perspiciatis saepe aperiam nulla tempore reiciendis. Magnam ipsa, est qui quam consequuntur laborum dolore.
        Unde eum tenetur iure ducimus deleniti sed voluptatem ex, consequatur dolorem numquam aperiam facilis ad voluptatum nam, minus aspernatur? Illum molestias, quos laudantium quas odio repellendus vel voluptate minus ipsa.
        Doloribus et iusto rerum? Repellendus laborum odio optio eius inventore at delectus dignissimos rerum omnis deleniti minus eveniet aspernatur incidunt atque harum aut iusto modi quam, praesentium tempora. Est, qui?
        Consequuntur accusantium, archi<h2>123</h2>tecto suscipit, numquam at alias quasi cupiditate expedita maxime tempora commodi laboriosam sit, nisi ex voluptatibus? Laborum asperiores quisquam, debitis saepe tenetur delectus quidem odio a. Nihil, porro?
        Adipisci, perferendis doloribus. Odit, illo. Reiciendis suscipit quidem laboriosam voluptates consectetur ipsa veritatis provident perspiciatis dolor rerum, totam odio distinctio hic fuga corporis labore molestiae enim aliquid cupiditate asperiores voluptatem.`,
      },
]